version: '3'

services:
  # Database
  db_2:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  # phpmyadmin_2:
  #   depends_on:
  #     - db_2
  #   image: phpmyadmin/phpmyadmin
  #   restart: always
  #   ports:
  #     - '8088:80'
  #   environment:
  #     PMA_HOST: db_2
  #     MYSQL_ROOT_PASSWORD: password 
  #   networks:
  #     - wpsite
  # Wordpress
  wordpress_medcalsan:
    depends_on:
      - db_2
    image: wordpress:latest
    ports:
      - '8087:80'
    restart: always
    volumes:
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wordpress:/var/www/html
      - ./tema:/var/www/html/wp-content/themes/tema
    environment:
      WORDPRESS_DB_HOST: db_2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: