name: CI -> Deploy to My website

on:
  push:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          protocol: ${{secrets.FTP_PROTOCOL}}
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./tema/"
          server-dir: "/wp-content/themes/medicalsan-theme/"

      - name: Deploy to Development
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          protocol: ${{ vars.FTP_PROTOCOL_PRODUCTION }}
          server: ${{ vars.FTP_SERVER_PRODUCTION }}
          username: ${{ vars.FTP_USERNAME_PRODUCTION }}
          password: ${{ vars.FTP_PASSWORD_PRODUCTION }}
          local-dir: "./tema/"
          server-dir: "/wp-content/themes/medicalsan-theme/"
